### PR TITLE
OSPO-Book: update linter configuration

### PR DESCRIPTION
**Pull request by gkunz**
This updates the configuration of the markdown linter in accordance with the changed location of the markdown files for the new website.

### CODE REVIEW

**Comment by gkunz** [comment]
Hi @cjyabraham. Thanks for preparing the website of the OSPO book!

I'd like to ask you about the intended way forward for the format of the references in [the table here](https://github.com/todogroup/ospology/blob/main/ospo-book/content/en/references.md). Do we want to keep separate columns for title and the URL or should we combine both into a normal clickable link (using the usual \[title\](url) markdown syntax?

I am actually just wondering because the markdown linter recommends to not use blank URLs. We can of course decide what we want.

Thanks

**Comment by cjyabraham** [comment]
Hi @gkunz, I'd recommend making the titles clickable links. I think that would look cleanest and provide the best user experience.

Have you seen the dev site [here](https://ospobook.netlify.app/) and [the references page is here for now](https://ospobook.netlify.app/references/)?

**Comment by gkunz** [comment]
Yes, Ana showed those on some calls.

I will then - later this weekend / beginning of next week - push an update to make those links clickable and thereby the linker happy.

Thanks!

**Comment by cjyabraham** [comment]
Ok, sounds good. Also, rather than having the links in a table like that with "Source" repeated down the left column, you could just use "Source" as a sub-heading and then just list the titles in a bulleted list below each sub-heading. Just an idea :)

**Comment by anajsana** [comment]
LGTM!

**Review by cjyabraham — APPROVED** [review]

**Pull request merged**
