### PR TITLE
OSPO mindmap automatically generate HTML in CI

### PR DESCRIPTION
**Pull request by mfix22**
TODO: 

- [x] Rebase on `main` after #178 merges
---

@anajsana @tsteenbe I believe this will work, but we need to set the Netlify "build command" ([see docs here](https://docs.netlify.com/configure-builds/overview/#basic-build-settings)) to

```sh
npm run build --if-present
```

or maybe 
```sh
cd ospo-mindmap && npm run build --if-present
```

### CODE REVIEW

**Comment by anajsana** [comment]
@mfix22 Thank you, this looks great so far. I can access Netlify dashboard to set the build command and establish a publish directory. Let me see what I can do 👍

**Comment by mfix22** [comment]
Shared this with @anajsana offline, but here are the Netlify config changes we need:

**Base directory**: `ospo-mindmap`
**Build command**: `npm run build --if-present`
**Publish directory**: `Public/` (might be ospo-mindmap/Public/ but I don’t think it is)

**Comment by anajsana** [comment]
@mfix22 I've retried the deploy with the new settings but it dropped an error location when executing `npm run build --if-present` in build command

**Comment by anajsana** [comment]
Thanks @mfix22 ! Looks like the deploy preview is working nicely 🤩 Merging 🚀

**Pull request merged**
