### PR TITLE
[OSPO Book] Make title of chapter 3 more clear

### PR DESCRIPTION
**Pull request by cornelius**
I found the title of chapter 3 a bit misleading. The chapter focus on what the daily operations are and how to structure them, not so much about learning how to do them. This is a suggestion how to make this clearer in the title of the chapter.

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]

**Review by anajsana — APPROVED** [review]

**Comment by node** [comment]
It make sense. 👍

**Comment by UlisesGascon** [comment]
I solved the conflict and I will merge the changes as the deployment was fine and the titles are working as expected.

**Review by UlisesGascon — APPROVED** [review]

**Comment by UlisesGascon** [comment]
Not sure why is not allowing me to merge it as the conflicts were solved in 0693877

Screenshot 2024-01-19 at 10 46 47

**Comment by anajsana** [comment]
@cornelius @UlisesGascon @node  This PR has the same issue as the one that Shilla submitted (https://github.com/todogroup/ospology/pull/398). Is making changes to an old branch that did not have the website deployment integrated, and the updated one has a completely different folder structure and content. So, again, I suggest creating a new PR and tag this as duplicated to unblock this issue https://github.com/todogroup/ospology/pull/398again, I suggest creating a new PR and making this as duplicated to unblock this issue

**Comment by anajsana** [comment]
As agreed durign today's contributor's call (AMER & EMEA session ( I will close this since chapter title has been moved to 4 👍  )

**Pull request closed without merging**
