### PR TITLE
Add Sourav to TODO OSPOlogy Maintainer

### PR DESCRIPTION
**Pull request by souravcipher**
Hi, I'm interested to become a maintainer of the TODO OSPOlogy Project. I have been contributing to the TODO Group for a long time now. 

Here are a few contributions of mine to the TODO Group
- I stand # 2 in the OSPOlogy [contributor's graph](https://github.com/todogroup/ospology/graphs/contributors)
- I have a couple of PRs (merged) in the OSPOlogy repo my [PRs](https://github.com/todogroup/ospology/pulls?q=is%3Apr+author%3Asouravcipher+is%3Aclosed)
- I have attended many regional, community calls and events at TODO Group.

About my recent contributions in open source and inner source
- Founder at @OpenPrivacyTech
- Member ISPO WG at @InnerSourceCommons
- Led open source communities in prev companies. 
- Led Technical Mentorship Program for Private AI Series at @OpenMined
- Led open source programs like Google Summer of Code, and Season of Docs as org admin.
- Mentored at Google Code-in for @TensorFlow org. 
- And volunteered with a couple of other open source and nonprofit organizations.

I look forward to making more impact and promoting TODO Group and its mission by becoming a Maintainer.
Thank you and looking forward to hearing you!

### CODE REVIEW

**Comment by souravcipher** [comment]
Apologies, I made a mistake by committing in the settings.yml, when I clicked in the [settings.yml file](https://github.com/todogroup/ospology/blob/main/.github/settings.yml#L18) from the my forked repo in the governance file it redirected me to the main branch and I did not notice as there are too many tabs opened in my browser. I will be careful next time. 

I think we also need to have a guide and change permission for the members so that all the commits should be with PRs only for members. Thanks.

**Comment by anajsana** [comment]
Thanks @souravcipher 👍  I've pinged your requests to the OSPOlogy maintainers for review and will get back to you ASAP! 😊

**Comment by souravcipher** [comment]
Thank you, Ana! Looks like this PR got closed due to my new commit for #294

This is still going. 🚀

**Comment by anajsana** [comment]
@souravcipher can you re-open the PR until we review and approve it? 🙂

**Comment by souravcipher** [comment]
> @souravcipher can you re-open the PR until we review and approve it? 🙂 

Can you just review and merge #294. I'll open this PR and push the changes asap for review!

It's not allowing me to open it due to my new PR.

**Comment by anajsana** [comment]
@caniszczyk when you have some time, can you please review ? 🙂 Thank you!

**Comment by caniszczyk** [comment]
LGTM +1

**Review by caniszczyk — APPROVED** [review]

**Comment by souravcipher** [comment]
Thank you @caniszczyk @anajsana !! 🥳

**Pull request merged**
