### PR TITLE
OSPO mindmap install guide 

### PR DESCRIPTION
**Pull request by mfix22**
* Add `package.json` to facilitate installing `markmap` dependencies and running the generation script
* Update the README contributing instructions
* Fix typos.

Follow up (in future PR)
- [ ] Update build to automatically generate new HTML during CI (#179)

### CODE REVIEW

**Comment by mfix22** [comment]
PTAL @tsteenbe 🙂

**Comment by mfix22** [comment]
Let me know if there are any blockers here @anajsana @tsteenbe 🙂 No rush on the review though!

**Comment by anajsana** [comment]
> Let me know if there are any blockers here @anajsana @tsteenbe 🙂 No rush on the review though!

Hello @mfix22 ! I'm planning to work on this PR during today's WDA meeting and hopefully, they will be merged by the end of the session (from 15:30 – 17:30 UTC) (cc @tsteenbe )

**Comment by anajsana** [comment]
Installation guide update LGTM. Merging this PR 👍  Thanks for contributing to this @mfix22 !

**Pull request merged**
